name: CI/CD Pipeline for Frontend and Backend

on:
  push:
    branches:
      - final-prod
  pull_request:
    branches:
      - final-prod

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Frontend Setup and Build
      - name: Set Up Node.js for Frontend
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies for Frontend
        working-directory: ./country-dashboard-frontend
        run: npm ci

      - name: Build Frontend
        working-directory: ./country-dashboard-frontend
        run: npm run build

      - name: Test Frontend
        working-directory: ./country-dashboard-frontend
        run: npm test -- --coverage

      # Backend Setup
      - name: Set Up Node.js for Backend
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies for Backend
        working-directory: ./country-dashboard-backend
        run: npm ci

      # Skip Backend Tests
      - name: Skip Backend Tests
        working-directory: ./country-dashboard-backend
        run: echo "Skipping backend tests"

      # Upload Frontend Coverage Report
      - name: Upload Frontend Coverage Report
        if: always()
        working-directory: ./country-dashboard-frontend
        uses: actions/upload-artifact@v3
        with:
          name: frontend-coverage-report
          path: coverage/

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/final-prod'

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Deploy Frontend to Vercel
      - name: Deploy Frontend to Vercel
        working-directory: ./country-dashboard-frontend
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ZTHIYmBZ9a4pP7SJC1bIOnsN
          vercel-args: "--prod"
          github-token: ${{ secrets.GITHUB_TOKEN }}

      # Backend Deployment Placeholder
      - name: Deploy Backend
        working-directory: ./country-dashboard-backend
        run: |
          echo "Deploy Backend Application (e.g., to a server or cloud service)"
