name: CI/CD Pipeline for Frontend and Backend

on:
  push:
    branches:
      - production
  pull_request:
    branches:
      - production

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Frontend Setup and Build
    - name: Set Up Node.js for Frontend
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Dependencies for Frontend
      working-directory: ./country-dashboard-frontend
      run: npm ci

    - name: Build Frontend
      working-directory: ./country-dashboard-frontend
      run: npm run build

    - name: Test Frontend
      working-directory: ./country-dashboard-frontend
      run: npm test -- --coverage

    # Backend Setup and Build
    - name: Set Up Node.js for Backend
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Dependencies for Backend
      working-directory: ./country-dashboard-backend
      run: npm ci

    - name: Test Backend
      working-directory: ./country-dashboard-backend
      run: npm test -- --coverage

    # Upload Coverage Reports
    - name: Upload Frontend Coverage Report
      if: always()
      working-directory: ./country-dashboard-frontend
      uses: actions/upload-artifact@v3
      with:
        name: frontend-coverage-report
        path: coverage/

    - name: Upload Backend Coverage Report
      if: always()
      working-directory: ./country-dashboard-backend
      uses: actions/upload-artifact@v3
      with:
        name: backend-coverage-report
        path: coverage/

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/production'

    steps:
    # Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Frontend Deployment
    - name: Deploy Frontend
      working-directory: ./country-dashboard-frontend
      run: |
        echo "Deploy Frontend Build (e.g., to S3 or static hosting service)"

    # Backend Deployment
    - name: Deploy Backend
      working-directory: ./country-dashboard-backend
      run: |
        echo "Deploy Backend Application (e.g., to a server or cloud service)"
