name: CI/CD for Frontend and Backend to Vercel

on:
  push:
    branches:
      - final-prod
  pull_request:
    branches:
      - final-prod

jobs:
  frontend:
    name: Build and Deploy Frontend to Vercel
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: |
          cd country-dashboard-frontend
          npm install --legacy-peer-deps

      - name: Build Frontend
        run: |
          cd country-dashboard-frontend
          npm run build

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: '--prod'
          working-directory: ./country-dashboard-frontend

  backend:
    name: Build and Deploy Backend to Vercel
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: |
          cd country-dashboard-backend
          npm install

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: '--prod'
          working-directory: ./country-dashboard-backend
