name: CI/CD Pipeline

on:
  push:
    branches:
      - production
  pull_request:
    branches:
      - production

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Set up Node.js environment
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    # Install dependencies (set working-directory if package.json is in a subfolder)
    - name: Install Dependencies
      working-directory: ./backend  # Change to the correct folder where package.json exists
      run: npm ci

    # Run tests and generate coverage
    - name: Run Tests and Coverage
      working-directory: ./backend  # Change to the correct folder where package.json exists
      run: npm test -- --coverage

    # Upload coverage report to GitHub artifact
    - name: Upload Coverage Report
      if: always()
      working-directory: ./backend  # Change to the correct folder where package.json exists
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage/

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/production'

    steps:
    # Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Set up Node.js environment
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    # Install dependencies
    - name: Install Dependencies
      working-directory: ./backend  # Change to the correct folder where package.json exists
      run: npm ci

    # Deploy application
    - name: Deploy Application
      working-directory: ./backend  # Change to the correct folder where your deployment logic resides
      run: |
        echo "Deploy your application here"
