name: Deploy to Production

on:
  push:
    branches: [final-prod]

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Checkout backend code
        run: git checkout final-prod -b deploy-backend
      - name: Build and Deploy Backend
        run: |
          cd country-dashboard-backend
          # Install dependencies and build the backend
          npm install
          npm run build
          # Deploy to your preferred platform (e.g., Heroku, AWS, GCP)
          # Example for Heroku:
          heroku container:push web
          heroku container:release web

  deploy-frontend:
    runs-on: ubuntu-latest
    needs: deploy-backend
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Checkout frontend code
        run: git checkout final-prod -b deploy-frontend
      - name: Build and Deploy Frontend
        run: |
          cd country-dashboard-frontend
          # Install dependencies and build the frontend
          npm install
          npm run build
          # Deploy to your preferred platform (e.g., GitHub Pages, Netlify)
          # Example for GitHub Pages:
          git add -A
          git commit -m "Deploy to GitHub Pages"
          git push origin HEAD:gh-pages
